version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: services_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8000/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    command: ["run", "0.0.0.0"]
    depends_on:
      django:
        condition: services_healthy

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: exampledb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U exampleuser -d exampledb"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
